CampusMap/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.contrib.auth.views import login, logout

admin.autodiscover()

urlpatterns = patterns('map.views',
                      # url(r'^login/$', 'django_test.views.login'),
                      # url(r'^logout/$', 'django_test.views.logout'),
    url(r'^accounts/login/$', 'login'),
    url(r'^accounts/logout/$','logout'),
    url(r'^accounts/profile/$','home'),

    url(r'^$', 'home'),
    url(r'^home/$', 'home'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^course/$', 'course'),
    url(r'^module/', 'module'),
    url(r'^rooms/$', 'room'),
    url(r'^colour/$', 'colour'),
    url(r'^building/$', 'building'),
    url(r'^lecturer/$', 'lecturer'),
    url(r'^timetable/$', 'timetable'),
    url(r'^edit-timetable/$', 'editTimetable'),
    url(r'^department/$', 'department'),
    url(r'^edit-map-json/$', 'editMapJson'),
    url(r'^json/', 'JSON'),
    url(r'^JSON/', 'JSON'),
)

map/models.py
from django.db import models


class Department(models.Model):
    depName = models.CharField(max_length = 70, primary_key=True)

    def __str__(self):
        return "%s" % self.depName

class Course(models.Model):
    courseCode = models.CharField(max_length = 7, primary_key=True)
    courseName = models.CharField(max_length = 50)
    department = models.ForeignKey(Department)

    def __str__(self):
        return self.courseCode

class Colour(models.Model):
    colour = models.CharField(max_length = 10)
    hex = models.CharField(max_length=6, primary_key=True)

    def __str__(self):
        return "%s" % self.colour

class Module(models.Model):
    modCode = models.CharField(max_length = 7, primary_key=True)
    modName = models.CharField(max_length = 70)
    color = models.ForeignKey(Colour, default='FFFFFF')

    def __str__(self):
        return self.modCode


class Building(models.Model):

    buildingName = models.CharField(max_length = 75, primary_key=True)

    def __str__(self):
        return "%s" % self.buildingName


class Room(models.Model):
    roomCode = models.CharField(max_length = 15, primary_key=True) # changed to 15
    roomName = models.CharField(max_length = 30)
    building = models.ForeignKey(Building)
    lat = models.FloatField(max_length = 19, default= 53.27980291, editable=False)
    lng = models.FloatField(max_length = 19, default=-9.06089351, editable=False)

    def __str__(self):
        return self.roomCode


class Lecturer(models.Model):
    lecCode = models.CharField(max_length = 7, primary_key=True)
    lecFirst_Name = models.CharField(max_length = 50)
    lecLast_Name = models.CharField(max_length = 50)
    lecEmail = models.EmailField();

    def __str__(self):
        return self.lecFirst_Name + " " + self.lecLast_Name



class Timetable(models.Model):
    courseCode = models.ForeignKey(Course)
    year = models.CharField(max_length = 1)
    semester = models.CharField(max_length = 1, choices=(('1','1'), ('2','2')))

    class Meta:
        unique_together = (("year", "semester", "courseCode"),)

    def __str__(self):
        return "%s" % self.courseCode + " year:" + self.year + " sem:" + self.semester


class TimeEntry(models.Model):

    DAY_CHOICES = (
        ('1', 'Monday'),
        ('2', 'Tuesday'),
        ('3', 'Wednesday'),
        ('4', 'Thursday'),
        ('5', 'Friday'),
    )

    HOURS_CHOICES = (
        ('1', '09:00'),
        ('2', '10:00'),
        ('3', '11:00'),
        ('4', '12:00'),
        ('5', '13:00'),
        ('6', '14:00'),
        ('7', '15:00'),
        ('8', '16:00'),
        ('9', '17:00'),
        ('10', '18:00'),
        ('11', '19:00'),
    )

    timeTable = models.ForeignKey(Timetable)
    modCode = models.ForeignKey(Module)
    roomCode = models.ForeignKey(Room)
    day = models.CharField(max_length = 1, choices=DAY_CHOICES)
    time = models.CharField(max_length = 2, choices=HOURS_CHOICES)
    lecCode = models.ForeignKey(Lecturer)

    class Meta:
        unique_together = (("timeTable", "day", "time"),)

map/forms.py
from django import forms
from django.template.defaultfilters import mark_safe

from .models import Course, Module, Lecturer, Room, Building, Timetable, Department, TimeEntry, Colour

class DepartmentForm(forms.ModelForm):

    depName = forms.CharField(max_length = 50,label = mark_safe('<strong>Department Name</strong>'))

    class Meta:
        model = Department
        fields = "__all__"

class ColourForm(forms.ModelForm):

    colour = forms.CharField(max_length = 50,label = mark_safe('<strong>Colour</strong>'))
    hex = forms.CharField(max_length = 50,label = mark_safe('<strong>Hex Code</strong>'))


    class Meta:
        model = Colour
        fields = "__all__"


class CourseForm(forms.ModelForm):

    courseCode = forms.CharField(max_length=15,label = mark_safe('<strong>Code</strong>'))
    courseName = forms.CharField(max_length=50,label = mark_safe('<strong>Name</strong>'))
    department = queryset=Department.objects.all()

    class Meta:
        model = Course
        fields = "__all__"

class ModuleForm(forms.ModelForm):

    modCode = forms.CharField(max_length=7, label = mark_safe('<strong>Module Code</strong>'))
    modName = forms.CharField(max_length=70,label = mark_safe('<strong>Module Name</strong>'))
    colour = Colour.objects.all()

    class Meta:
        model = Module
        fields = "__all__"

class BuildingForm(forms.ModelForm):

    buildingName = forms.CharField(max_length = 75,label = mark_safe('<strong>Building Name</strong>'))

    class Meta:
        model = Building
        fields = "__all__"

class RoomForm(forms.ModelForm):

    roomCode = forms.CharField(max_length = 15,label = mark_safe('<strong>Room Code</strong>'))
    roomName = forms.CharField(max_length = 30,label = mark_safe('<strong>Room Name</strong>'))
    building = queryset=Building.objects.all()
    #lat = forms.CharField(max_length = 19, label = mark_safe('<strong>Latitude</strong>'))
    #lng = forms.CharField(max_length = 19, label = mark_safe('<strong>Longitude</strong>'))

    class Meta:
        model = Room
        fields = "__all__"

class LecturerForm(forms.ModelForm):

    lecCode = forms.CharField(max_length = 7,label = mark_safe('<strong>Code</strong>'),)
    lecFirst_Name = forms.CharField(max_length = 50,label = mark_safe('<strong>First Name</strong>'))
    lecLast_Name = forms.CharField(max_length = 50,label = mark_safe('<strong>Last Name</strong>'))
    lecEmail = forms.EmailField(label = mark_safe('<strong>Email</strong>'))
    class Meta:
        model = Lecturer
        fields = "__all__"

class TimetableForm(forms.ModelForm):

    courseCode = Course.objects.all()
    year = forms.CharField(max_length = 1)
    semester = forms.CharField(max_length = 1)
    class Meta:
        model = Timetable
        fields = "__all__"

class TimeEntryForm(forms.ModelForm):

    DAY_CHOICES = (
        ('1', 'Monday'),
        ('2', 'Tuesday'),
        ('3', 'Wednesday'),
        ('4', 'Thursday'),
        ('5', 'Friday'),
    )

    HOURS_CHOICES = (
        ('1', '09:00'),
        ('2', '10:00'),
        ('3', '11:00'),
        ('4', '12:00'),
        ('5', '13:00'),
        ('6', '14:00'),
        ('7', '15:00'),
        ('8', '16:00'),
        ('9', '17:00'),
        ('10', '18:00'),
        ('11', '19:00'),
    )

    timeTable = Timetable.objects.all()
    modCode = Module.objects.all()
    roomCode = Room.objects.all()
    lecCode = Lecturer.objects.all()
    day = forms.ChoiceField(choices=DAY_CHOICES)
    time = forms.ChoiceField(choices=HOURS_CHOICES)

    class Meta:
        model = TimeEntry
        fields = "__all__"

map/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from .forms import CourseForm, ModuleForm, RoomForm, LecturerForm, BuildingForm, TimetableForm, DepartmentForm,TimeEntryForm, ColourForm

from .models import Course, Timetable, Building, Module, Lecturer, Department, TimeEntry, Room, Colour
from django.shortcuts import render_to_response
from django.template import RequestContext

from django.core.context_processors import csrf
from django.contrib import  auth

import json, urllib, urlparse

from django.contrib.auth.decorators import login_required


def login(request):
    c = {} # create dict
    c.update(csrf(request)) # push csrf object to it

    username = request.POST.get('username', '')
    password = request.POST.get('password', '')
    user = auth.authenticate(username=username, password=password)

    if user is not None:
        auth.login(request,user)
        return HttpResponseRedirect('/home/') # Redirect after POST
    else:
        return HttpResponseRedirect('/home/') # Redirect after POST

def logout(request):
    auth.logout(request)
    return HttpResponseRedirect('/home/') # Redirect after POST


@login_required
def editTimetable(request):

    #Variables that are sent back to timetable.html to reload timetable after post
    check = 'false'
    c = 'null'
    y = 'null'
    s = 'null'

    if request.method == 'POST': # If the form has been submitted...
        form = TimeEntryForm(request.POST) # A form bound to the POST data

        if form.is_valid():
            save_it = form.save()
            save_it.save()

            #gets timeTable object from database and extracts course, year and semester values from it
            id = request.POST.get('timeTable','')
            t = Timetable.objects.all().get(id=id)
            t = str(t)
            t = t.split(' ')
            c = t[0]
            y = t[1].split('year:')[1]
            s = t[2].split('sem:')[1]
            check = 'true'
    else:
        form = TimeEntryForm() # An unbound form


    return render(request, 'timetable.html', {
        'form': form,
        'check': check,
        'course': c,
        'year': y,
        'sem': s
    })


def editMapJson(request):

    message = request.GET.get('message')

    if (message == 'buildings'):

        b = Building.objects.all()

        temp = []

        for o in b.iterator():
            temp.append(o.buildingName)
        data = {'buildings' : temp}

        return JsonResponse(data)

    elif (message == 'rooms'):

        print message

        r = Room.objects.all()
        b = request.GET.get('building')

        temp = []
        for o in r.iterator():
            if o.building.buildingName == b:
                temp.append(o.roomCode)

        data = {'rooms' : temp}

        print data

        return JsonResponse(data)

    elif (message == 'coord'):

        room = request.GET.get('room')

        r = Room.objects.get(roomCode=room)

        print r.lat

        data = {'lat' : r.lat, 'lng' : r.lng}

        return JsonResponse(data)

    elif (message == 'newCoord'):

        try:
            room = request.GET.get('room')
            r = Room.objects.get(roomCode=room)
            print str(request.GET.get('lat'))
            r.lat = float(request.GET.get('lat'))
            r.lng = float(request.GET.get('lng'))
            r.save()
            response = HttpResponse("success")
        except Exception:
            response = HttpResponse("failed")

        return response

    else:

        return HttpResponse("Invalid Query")


# Handles JSON requests
def JSON(request):

    message = urllib.unquote(request.get_full_path()).split('/json/?message=') # Gets JSON message sent from webpage
    #Splits message into parts
    submessage = message[1].split('&')
    dept = submessage[1].split('department=')[1]
    course = submessage[2].split('course=')[1]
    year = submessage[3].split('year=')[1]
    semester = submessage[4].split('semester=')[1]

    d = Department.objects.all()
    c = Course.objects.all()
    t = Timetable.objects.all()

    exists = False

    # returns list of available courses
    if (submessage[0] == 'courses'):
        temp = []

        for o in c.iterator():
            if o.department.depName == dept:
                temp.append(o.courseCode)

        data = {'courses' : temp}

        return JsonResponse(data)

    #returns a list of available departments
    elif (submessage[0] == 'departments'):
        temp = []

        for dept in d.iterator():
            temp.append(dept.depName)

        data = {'departments' : temp}

        return JsonResponse(data)

    #returns course codes for year filtering in timetable.html
    elif (submessage[0] == 'years'):
        temp = []
        for o in t.iterator():
            if course == o.courseCode.courseCode and o.semester == '1':
                temp.append(o.courseCode.courseCode)

        data = {'years' : temp}

        return JsonResponse(data)

    #loads timetable
    elif (submessage[0] == 'load'):
        # checks for queried course
        for o in c.iterator():
            if course == o.courseCode:
                exists = True

        if (exists):

            cs = Course.objects.get(courseCode=course)

            timetable = []

            t = TimeEntry.objects.filter(timeTable=Timetable.objects.get(courseCode=cs,year=year,semester=semester)) #filters out desired timetable using variables obtained from JSON message

            for o in t.iterator():

                tempData = {
                    'mod' : o.modCode.modCode,
                    'room' : o.roomCode.roomName,
                    'lec' : o.lecCode.lecFirst_Name + " " + o.lecCode.lecLast_Name,
                    'day' : o.day,
                    'time' : o.time,
                    'colour' : o.modCode.color.hex
                }

                timetable.append(tempData)

            data = {
                'code' : message,
                'title' : cs.courseName,
                'year':year,
                'semester':semester,
                'department' : cs.department.depName,
                'timetable' : timetable
            }

            return JsonResponse(data)

        else:
            return JsonResponse({'Timetable Not Found' : 'null'})

    else:
        return JsonResponse({'Invalid Query' : 'null'})


def home(request):

    check = 'false'
    c = 'null'
    y = 'null'
    s = 'null'

    if request.method == 'POST': # If the form has been submitted...
        form = TimeEntryForm(request.POST) # A form bound to the POST data

        if form.is_valid():
            save_it = form.save()
            save_it.save()

            id = request.POST.get('timeTable','')
            t = Timetable.objects.all().get(id=id)
            tt = str(t)
            ttt = tt.split(' ')
            c = ttt[0]
            y = ttt[1].split('year:')[1]
            s = ttt[2].split('sem:')[1]
            check = 'true'
    else:
        form = TimeEntryForm() # An unbound form

    return render(request, 'home.html', {
        'form': form,
        'check': check,
        'course': c,
        'year':y,
        'sem':s
    })

@login_required
def course(request):
    # get all data from course table in ascending order
    query_results = Course.objects.all().order_by('courseCode')

    if request.method == 'GET':
        message = request.GET.get('message')

        if message == 'delete':
            record = request.GET.get('toDelete')
            Course.objects.filter(courseCode=record).delete()
            #return HttpResponseRedirect('/timetable/')

    if request.method == 'POST': # If the form has been submitted...
        form = CourseForm(request.POST) # A form bound to the POST data
        if form.is_valid(): # All validation rules pass
            # Process the data in form.cleaned_data
            # ...

            save_it = form.save()
            save_it.save()
            return HttpResponseRedirect('/course/') # Redirect after POST
    else:
        form = CourseForm() # An unbound form

    return render_to_response('dbstuff/addcourse.html', locals(),context_instance=RequestContext(request))

@login_required
def module(request):
    # get all data from module table in ascending order
    query_results = Module.objects.all().order_by('modCode')

    if request.method == 'GET':
        message = request.GET.get('message')

        if message == 'delete':
            record = request.GET.get('toDelete')
            Module.objects.filter(modCode=record).delete()

    if request.method == 'POST': # If the form has been submitted...
        form = ModuleForm(request.POST) # A form bound to the POST data
        if form.is_valid(): # All validation rules pass
            # Process the data in form.cleaned_data
            # ...

            save_it = form.save()
            save_it.save()
            return HttpResponseRedirect('/module/') # Redirect after POST
    else:
        form = ModuleForm() # An unbound form

    return render_to_response('dbstuff/addmodule.html', locals(),context_instance=RequestContext(request))

@login_required
def room(request):
    query_results = Room.objects.all().order_by('roomCode', 'building')

    if request.method == 'GET':
        message = request.GET.get('message')

        if message == 'delete':
            record = request.GET.get('toDelete')
            Room.objects.filter(roomCode=record).delete()
            #return HttpResponseRedirect('/timetable/')

    if request.method == 'POST': # If the form has been submitted...
        form = RoomForm(request.POST) # A form bound to the POST data
        if form.is_valid(): # All validation rules pass
            # Process the data in form.cleaned_data
            # ...

            save_it = form.save()
            save_it.save()
            return HttpResponseRedirect('/rooms/') # Redirect after POST
    else:

CampusMap/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>CampusMap</title>

    <!-- Bootstrap Core CSS -->
    <link href="{{ STATIC_URL }}css/bootstrap.min.css" rel="stylesheet">
    <!-- Custom CSS -->
    <link href="{{ STATIC_URL }}css/simple-sidebar.css" rel="stylesheet">
    <!-- jQuery -->
    <script src="{{ STATIC_URL }}js/jquery.js"></script>
    <!-- Bootstrap Core JavaScript -->
    <script src="{{ STATIC_URL }}js/bootstrap.min.js"></script>
    <!-- Menu Toggle Script -->
    <script src="{{ STATIC_URL }}js/bootbox.min.js"></script>
    <!-- Map -->
    <script type="text/javascript" src="{{ STATIC_URL }}js/map.js"> </script>
    <!-- DB operations -->
    <script type="text/javascript" src="{{ STATIC_URL }}js/sm.js"> </script>

</head>

<style>

    .top-custom{
        padding:15px
    }

</style>


<body>
<div id="wrapper">



    <!-- Sidebar -->
    <div id="sidebar-wrapper">

        <ul class="sidebar-nav" >
            <li class="sidebar-brand">
                <a style="color:white">
                    NUI Galway CampusMap
                </a>
            </li>
            <li>
                <a style="color:white" href="../home"><span class="glyphicon glyphicon-home" aria-hidden="false" ></span> Home</a>
            </li>
            <li>
                <a style="color:white" href="../edit-timetable"><span class="glyphicon glyphicon-th-large" aria-hidden="false"></span> Edit a Timetable</a>
            </li>

            <hr>
            <ul style="color:white"> <span class="glyphicon glyphicon-menu-hamburger" aria-hidden="false"></span> Database
                <li>
                    <a href="../course">Add Course</a>
                </li>
                <li>
                    <a href="../module">Add Module</a>
                </li>
                <li>
                    <a href="../rooms">Add Room</a>
                </li>
                <li>
                    <a href="../building">Add Building</a>
                </li>
                <li>
                    <a href="../department">Add Department</a>
                </li>
                <li>
                    <a href="../lecturer">Add Lecturer</a>
                </li>
                <li>
                    <a href="../timetable">Add Timetable</a>
                </li>
                <li>
                    <a href="../colour">Add Colour</a>
                </li>

            </ul>
<!--    Logout button in the side pane... using now one in the top nav bar
             <a href="/accounts/logout/" class="btn btn-danger" aria-label="Left Align" style="width: 100%">
                <span class="glyphicon glyphicon-user" aria-hidden="true"></span> Logout
            </a>
            -->
        </ul>

    </div>
{% include "dbstuff/login.html" %}
    <!-- /#sidebar-wrapper -->

    <!-- Page Content -->
    <div id="page-content-wrapper">

        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-2 col-md-2 col-sm-4 col-xs-4 text-center top-custom">
                    <a href="#menu-toggle" class="btn btn-primary" id="menu-toggle">Toggle Menu</a>
                </div>

                {% block header %}

                {% endblock header %}
            </div>

            {% block content %}

            {% endblock content%}

        </div>
    </div>
    <!-- /#page-content-wrapper -->

    <hr>
    <footer class="footer" align="center" style="text-align: center">
        <p>&copy; CampusMap 2015</p>
    </footer>

</div> <!-- /wrapper -->
</body>

<script>
    $("#menu-toggle").click(function(e) {
        e.preventDefault();
        $("#wrapper").toggleClass("toggled");
    });
</script>

</html>

CampusMap/templates/map.html
{%block content%}

<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAJJEeE5dn-hk6w1MoBSn2-Q3p4TfBcbMk"> </script>

<style type="text/css">

    #map-canvas {
        height: 100%;
        width: 100%;
        margin-left: 50px;
        margin-right: 50px;
        margin-top: 30px;
        padding: 0;
    }

    .full-height{
        height: 450px;
    }

    @media (min-height: 800px) {
        .full-height{
            height: 600px;
        }
    }

    @media (min-height: 900px) {
        .full-height{
            height: 700px;
        }
    }

    @media (min-height: 1000px) {
        .full-height{
            height: 850px;
        }
    }

</style>

    <div class="container full-height">
        <div id="map-canvas"></div>
    </div>






{%endblock%}

CampusMap/templates/timetable.html
{% extends "base.html" %}

{%block header%}

    <form role="form" xmlns="http://www.w3.org/1999/html">
        <div class="form-group container-fluid">
            <div class="col-lg-2 col-md-2 col-sm-4 col-xs-4 text-center top-custom">
                <select class="form-control" id="departmentSelect" >
                    <option value=''>Select Department</option>
                </select>
            </div>

            <div class="col-lg-2 col-md-2 col-sm-4 col-xs-4 text-center top-custom" id = "courses">
                <select class="form-control" id="courseSelect">
                    <option value='0'>Select Course</option>
                </select>
            </div>

            <div class="col-lg-2 col-md-2 col-sm-4 col-xs-4 text-center top-custom">
                <select class="form-control" id="yearSelect">
                    <option value='0'>Select Year</option>

                </select>
            </div>

            <div class="col-lg-2 col-md-2 col-sm-4 col-xs-4 text-center top-custom">
                <select class="form-control" id="semesterSelect">
                    <option value='0'>Select Semester</option>
                    <option value="1" >1</option>
                    <option value="2" >2</option>
                </select>
            </div>

            <div class="col-lg-2 col-md-2 col-sm-4 col-xs-4 text-center top-custom">
                <btn class="btn btn-primary" onclick="submit()">Search</btn>
            </div>

        </div>
    </form>


{%endblock header%}


{%block content%}

    <script src="{{ STATIC_URL }}js/table.js"></script>
    <script src="{{ STATIC_URL }}js/timetableFilters.js"></script>


    <style>

        table {
            width: 100%;
        }

        th {
            height: 60px;
            align: center;
        }

    </style>

    <div class="container-fluid col-md-11"></div>

    <div id="timetable" class="container-fluid col-md-11" style="margin:20px"></div>

    <div id="cellModal" class="modal fade">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title">Add a class to the timetable</h4>
                </div>
                <div class="modal-body" id="cellModalBody">


                    <form id="cellModalForm" action='' method='post' class="form">{% csrf_token %}

                        <div class="form-group"> <label for="timeTable" id="id_timeTable">Timetable</label>{{ form.timeTable }}</div>
                        <div class="form-group"> <label for="day" id="id_day">Day</label>{{ form.day }}</div>
                        <div class="form-group"> <label for="time" id="id_time">Time</label>{{ form.time }}</div>
                        <div class="form-group"> <label for="modCode">Module Code</label>{{ form.modCode }}</div>
                        <div class="form-group"> <label for="roomCode">Room Code</label>{{ form.roomCode }}</div>
                        <div class="form-group"> <label for="lecCode">Lecturer Name</label>{{ form.lecCode }}</div>

                        <!--</div>-->
                        <div class="modal-footer">
                            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                            <button type="submit" class="btn btn-primary">Save changes</button>
                        </div>

                    </form>
                </div>
            </div>
        </div>


        <script>

            window.onload=function(){
                getDepartments();

                // reloads the correct timetable after a class is added using the modal to allow you to
                // enter multiple classes without having to filter the timetable out
                // values for course, year and sem are returned from views.py
                if (({{ check }})==true){
                    loadTimetable('load','{{ course }}','{{ year }}','{{ sem }}')
                }

            }

            //Onclick to load timetable when semester is chosen
            function submit(){
                sem = document.getElementById('semesterSelect');
                year = document.getElementById('yearSelect');
                course = document.getElementById('courseSelect');

                var val1 = course.options[course.selectedIndex].value;
                var val2 = year.options[year.selectedIndex].value;
                var val3 = sem.options[sem.selectedIndex].value;

                sem.setAttribute('onchange', loadTimetable(department,val1,val2,val3));

                year = val2;
                semester = val3;
            }

            //Loads the timetable
            function loadTimetable(department,course,year,semester){

                var request = new XMLHttpRequest();
                var message = buildURL("load",department,course,year,semester);
                request.open('GET', message, false);  // `false` makes the request synchronous
                request.send(null);

                timeTable = JSON.parse(request.responseText);

                retDiv = createTable(timeTable, 'admin');

                el = document.getElementById("timetable");

                //Clears div when a new timetable is selected
                while (el.hasChildNodes()){
                    el.removeChild(el.firstChild);
                }

                document.getElementById("timetable").appendChild(retDiv);

                var table = document.getElementsByTagName("table")[0];
                var cells = table.getElementsByTagName("td"); //

                //Adds onclick events to each cell to load the modal for data input
                for(var i = 0; i < cells.length; i++) {
                    // Cell Object
                    var cell = cells[i];
                    // Track with onclick
                    cell.onclick = function(){
                        $('#cellModal').modal('show');
                    }
                }


            }


        </script>

{%endblock%}